/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaordersystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Chase Scallion
 */
public class OrderFrame extends javax.swing.JFrame {
    
    private PizzaOrderModel myModel;

    /**
     * Creates new form OrderFrame
     */
    public OrderFrame(PizzaOrderModel myModel) {
        this.myModel = myModel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox<>();
        toppingLabel = new javax.swing.JLabel();
        pepperoniCheckBox = new javax.swing.JCheckBox();
        chickenCheckBox = new javax.swing.JCheckBox();
        meatBallCheckBox = new javax.swing.JCheckBox();
        mushroomCheckBox = new javax.swing.JCheckBox();
        pepperCheckBox = new javax.swing.JCheckBox();
        orderButton = new javax.swing.JButton();
        onionCheckBox = new javax.swing.JCheckBox();
        returnButton = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("1213 Pizzeria");

        sizeLabel.setText("Select the size");

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 inches $9.25", "14 inches $10.95", "16 inches $12.95", "18 inches $14.95" }));
        sizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeComboBoxActionPerformed(evt);
            }
        });

        toppingLabel.setText("Select the toppings");

        pepperoniCheckBox.setText("Pepperoni ($1.50)");

        chickenCheckBox.setText("Chicken ($1.95)");

        meatBallCheckBox.setText("Meatballs ($1.80)");

        mushroomCheckBox.setText("Mushrooms ($1.50)");

        pepperCheckBox.setText("Peppers ($1.0)");

        orderButton.setText("Place Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        onionCheckBox.setText("Onions ($1.0)");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toppingLabel)
                            .addComponent(sizeLabel))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onionCheckBox)
                            .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pepperoniCheckBox)
                            .addComponent(chickenCheckBox)
                            .addComponent(meatBallCheckBox)
                            .addComponent(pepperCheckBox)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(returnButton)
                                .addComponent(mushroomCheckBox))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(orderButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeLabel)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toppingLabel)
                    .addComponent(pepperoniCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chickenCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meatBallCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pepperCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mushroomCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onionCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderButton)
                    .addComponent(returnButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //FIXME: Implement the event handler
    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
    int size = sizeComboBox.getSelectedIndex();
    PizzaOrder order = new PizzaOrder(size);
    
    
    if(pepperoniCheckBox.isSelected()){
        order.addTopping(Topping.PEPPERONI);
    }
    if(chickenCheckBox.isSelected()){
        order.addTopping(Topping.CHICKEN);
    }
    if(meatBallCheckBox.isSelected()){
        order.addTopping(Topping.MEATBALLS);
    }
    if(pepperCheckBox.isSelected()){
        order.addTopping(Topping.PEPPER);
    }
    if(mushroomCheckBox.isSelected()){
        order.addTopping(Topping.MUSHROOMS);
    }
    if(onionCheckBox.isSelected()){
        order.addTopping(Topping.ONIONS);
    }
    
    myModel.addOrder(order);
    
    JOptionPane.showMessageDialog(this, "Order is successfully placed.\nOrder number: " + order.getOrderNumber() + "\nSize: " + sizeComboBox.getSelectedItem() + "\n" + order.toppingToString());
    }//GEN-LAST:event_orderButtonActionPerformed
    
    //FIXME: Implement the event handler
    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
    this.dispose();
    MenuFrame myMenuFrame = new MenuFrame(myModel);
    myMenuFrame.setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    private void sizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chickenCheckBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox meatBallCheckBox;
    private javax.swing.JCheckBox mushroomCheckBox;
    private javax.swing.JCheckBox onionCheckBox;
    private javax.swing.JButton orderButton;
    private javax.swing.JCheckBox pepperCheckBox;
    private javax.swing.JCheckBox pepperoniCheckBox;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel toppingLabel;
    // End of variables declaration//GEN-END:variables
}
